<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Imagine Board</text>


        <Action name="imagine_board_extension_browse_minus">
          <icon></icon>
          <text>Browse Minus</text>
          <whatsThis></whatsThis>
          <toolTip></toolTip>
          <iconText></iconText>
          <activationFlags></activationFlags>
          <activationConditions></activationConditions>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
          <statusTip></statusTip>
        </Action>
        <Action name="imagine_board_extension_browse_plus">
          <icon></icon>
          <text>Browse Plus</text>
          <whatsThis></whatsThis>
          <toolTip></toolTip>
          <iconText></iconText>
          <activationFlags></activationFlags>
          <activationConditions></activationConditions>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
          <statusTip></statusTip>
        </Action>


    </Actions>
</ActionCollection>
