<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Imagine Board</text>


        <Action name="pykrita_imagine_board_extension_browse_minus">
          <text>Browse Minus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>
        <Action name="pykrita_imagine_board_extension_browse_plus">
          <text>Browse Plus</text>
          <shortcut>none</shortcut>
          <isCheckable>false</isCheckable>
        </Action>


    </Actions>
</ActionCollection>
